Diagnostics:
  ClangTidy:
    Add: [readability-*, llvm-*, modernize-*, google-*, misc-*, bugprone-*, clang-*, performance-*]
    Remove: [readability-identifier-length, modernize-use-trailing-return-type, readability-magic-numbers, readability-uppercase-literal-suffix, bugprone-easily-swappable-parameters, readability-braces-around-statements, google-readability-braces-around-statements, cppcoreguidelines-pro-type-cstyle-cast, google-readability-casting]
    CheckOptions:
      misc-non-private-member-variables-in-classes.IgnoreClassesWithAllMemberVariablesBeingPublic: true
  UnusedIncludes: Strict

Hover:
  ShowAKA: Yes
