Diagnostics:
  ClangTidy:
    Add: [readability-*, llvm-*, modernize-*, google-*, misc-*, bugprone-*, clang-*, performance-*]
    Remove: [modernize-use-trailing-return-type, readability-magic-numbers, readability-uppercase-literal-suffix]
  UnusedIncludes: Strict

Hover:
  ShowAKA: Yes
