Diagnostics:
  ClangTidy:
    Add: [llvm-*, modernize-*, google-*, misc-*, bugprone-*, clang-*, performance-*]
    Remove: [
      readability-identifier-length,
      modernize-use-trailing-return-type,
      modernize-avoid-c-arrays,
      modernize-pass-by-value,
      readability-uppercase-literal-suffix,
      readability-function-cognitive-complexity,
      bugprone-easily-swappable-parameters,
      misc-non-private-member-variables-in-classes,
      misc-definitions-in-headers,
      misc-no-recursion,
      modernize-use-nodiscard,
      google-explicit-constructor,
      readability-suspicious-call-arguments,
      readability-magic-numbers]
  UnusedIncludes: Strict

Hover:
  ShowAKA: Yes

CompileFlags:
  Add: -Wno-unknown-warning-option
  Remove: [-m*, -f*]
  #  Add: [-std=c++20]
