Diagnostics:
  ClangTidy:
    Add: [llvm-*, modernize-*, google-*, misc-*, bugprone-*, clang-*, performance-*]
    Remove: [
      readability-identifier-length,
      modernize-use-trailing-return-type,
      modernize-avoid-c-arrays,
      modernize-pass-by-value,
      readability-uppercase-literal-suffix,
      readability-function-cognitive-complexity,
      bugprone-easily-swappable-parameters,
      misc-non-private-member-variables-in-classes,
      misc-definitions-in-headers,
      misc-no-recursion,
      misc-use-internal-linkage,
      modernize-use-nodiscard,
      google-explicit-constructor,
      readability-suspicious-call-arguments,
      readability-magic-numbers,
      google-default-arguments,
      bugprone-narrowing-conversions,
      performance-enum-size,
      llvm-prefer-static-over-anonymous-namespace,
    ]
    FastCheckFilter: None
  UnusedIncludes: Strict

Hover:
  ShowAKA: true

InlayHints:
  DefaultArguments: true

Completion:
  AllScopes: true
  ArgumentLists: Delimeters
  HeaderInsertion: Never
  CodePatterns: All

CompileFlags:
  Add: -Wno-unknown-warning-option
  Remove: [-m*, -f*]
