## FIRST LINE/ROW: Info & Status
# First param ─┌
[username]
format = " [╭─$user]($style)@"
style_user = "bold blue"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold dimmed blue"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = "purple"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false

# Prompt: param 2 └─
[character]
success_symbol = " [╰─λ](bold blue)"
error_symbol = "[Σ](bold red)"

# SYMBOLS
[status]
format = '[ ╰─]($style)'
style = "blue"
map_symbol = true
disabled = false

[aws]
symbol = " "

[conda]
symbol = " "

[cmake]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "󰛥 "
